dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: WccLu9QAmBEY23sqUt4j+85ZS7tnjcC8qMq37hVJAEK1xUzUVfdfxAHHYIkO9nSYKIVxIrmVtevt1lsq8UY2E+lOJSsVUEuus54fjNCIdYaTrLYjag8VemL08754yqByq49Lz5Ah+YUvdrdIW0fn9v+saANRIIKooamj42hOPwpcNuOLbc6LNbVPKwlFTtyOfcXq7S9+wo+ptuDFJDViIdIlWSuuGo3CHMpEqKMCbXiyIHp/RDCbCNJegMT6Cafo8sZeVbzY+B/aLuqpQKvV452ZxJOwNwWbsIdodLkiZYFRg8pvZ62NJsq83V7UdCJurSjp0N6lB0UatjZMVrXRHKfCpwzFLwzrFEcsqyO8QzuJx/ZOTsOVz8Hi2i3NIaYwX0NnY/ujaAnxOUO7pxkA6HXLDzzTA5mu/pnA9EzXT8BjkfFAJZtNXEtLAcvWEYu5NyNnY5YH4grhn+nZLiTu3PaFOop2y8Qz40ovi+nP8zYdZzL09KJzw+P2uLI6N2aaf0bU3heq0XxSxDgNK5xj4cbZ4FDv7WdeuWeAHs4TxSoZu1Y3aGZQ0QNjANiYHdq+pLCfvoHjIU6lzePXAWdHUYkdbRJICmjF4F/cXQsDbI/FvBW7iLnvc1+9BFKr8pYUpSsACV8mPDfuQHZ3F89GYaYd1xv+X5N4i+FK85WB0Bg=
