version: '3.3'
services:

  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      mgmt_net:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      mgmt_net:

  ui:
    image: ${DOCKER_USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      front_net:
      mgmt_net:

  post:
    image: ${DOCKER_USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
      front_net:
        aliases:
          - post
      mgmt_net:

  comment:
    image: ${DOCKER_USERNAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
      mgmt_net:

  prometheus:
    image: ${DOCKER_USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    networks:
      front_net:
      mgmt_net:

volumes:
  post_db:

networks:
  front_net:
  back_net:
  mgmt_net:
